// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Game Of Life");

var component$1 = ReasonReact.statelessComponent("Tile");

function make(neighbours, _) {
  return /* record */[
          /* debugName */component$1[/* debugName */0],
          /* reactClassInternal */component$1[/* reactClassInternal */1],
          /* handedOffState */component$1[/* handedOffState */2],
          /* willReceiveProps */component$1[/* willReceiveProps */3],
          /* didMount */component$1[/* didMount */4],
          /* didUpdate */component$1[/* didUpdate */5],
          /* willUnmount */component$1[/* willUnmount */6],
          /* willUpdate */component$1[/* willUpdate */7],
          /* shouldUpdate */component$1[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          className: "tile"
                        }, String(neighbours));
            }),
          /* initialState */component$1[/* initialState */10],
          /* retainedProps */component$1[/* retainedProps */11],
          /* reducer */component$1[/* reducer */12],
          /* subscriptions */component$1[/* subscriptions */13],
          /* jsElementWrapped */component$1[/* jsElementWrapped */14]
        ];
}

var Tile = /* module */[
  /* component */component$1,
  /* make */make
];

var children = /* array */[
  /* record */[/* neighbours */0],
  /* record */[/* neighbours */1]
];

var createBoard = $$Array.make_matrix(30, 30, 1);

console.log(createBoard);

function mapRow(row) {
  return $$Array.map((function (row) {
                return ReasonReact.element(/* None */0, /* None */0, make(row, /* array */[]));
              }), row);
}

function make$1() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              var row = $$Array.map(mapRow, createBoard);
              return React.createElement("div", {
                          className: "container"
                        }, React.createElement("h2", {
                              className: "title"
                            }, "Game of Life"), React.createElement("div", {
                              className: "board"
                            }, Belt_Array.map(row, (function (cell) {
                                    return React.createElement("div", {
                                                className: "row"
                                              }, cell);
                                  }))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.Tile = Tile;
exports.children = children;
exports.createBoard = createBoard;
exports.mapRow = mapRow;
exports.make = make$1;
/* component Not a pure module */
